#!/usr/bin/env python

import os
from urllib.parse import urljoin
import logging
from datetime import datetime, timedelta
import requests
from requests.packages.urllib3.util.retry import Retry
from requests.adapters import HTTPAdapter
from tempfile import NamedTemporaryFile

logger = logging.getLogger(__name__)
logging.basicConfig(
    format='%(asctime)s %(levelname)-8s %(message)s',
    filename='portland-permits.log',
    level=logging.DEBUG)

date_format = '%m/%d/%Y'
api_url = 'https://www.portlandmaps.com/api/'
from_date = datetime.now() - timedelta(days=30)

session = requests.Session()
retries = Retry(total=5,
                backoff_factor=0.1,
                status_forcelist=[500, 502, 503, 504])

session.mount('https://', HTTPAdapter(max_retries=retries))


def fetch_permit_data(date_from, date_to=datetime.today().strftime(date_format)):
    params = {
        'date_type': 'issued',
        'date_from': date_from,
        'date_to': date_to,
        'sort_field': 'issued',
        'sort_order': 'desc',
        'format': 'json',
        'api_key': os.environ['PORTLAND_DEV_API_KEY']
    }

    r = session.get(urljoin(api_url, 'permit'), params=params)
    r.raise_for_status()
    return r


try:
    t = fetch_permit_data(date_from=from_date.strftime(date_format))
    print(t.json)
except requests.HTTPError as e:
    print('failed')
